#define NUM_ROWS 24
#define NUM_COLS 64

#define NUM_USER_ROWS 2

#define SERVER_FIRST_ROW 1
#define SERVER_LAST_ROW (NUM_ROWS - INPUT_LINES - 3)

#define USER_FIRST_ROW (NUM_ROWS - INPUT_LINES - 1)
#define USER_LAST_ROW (NUM_ROWS - 2)

#define FIRST_COL 0
#define LAST_COL (NUM_COLS - 1)

#define CURSOR_COL(x) (x % NUM_COLS + FIRST_COL)
#define CURSOR_ROW(x) (x / NUM_COLS + USER_FIRST_ROW)