#define SERVER_FIRST_ROW 1
#define SERVER_LAST_ROW 19

#define USER_FIRST_ROW 21
#define USER_LAST_ROW 22
#define NUM_USER_ROWS (USER_LAST_ROW - USER_FIRST_ROW + 1)

#define FIRST_COL 0
#define LAST_COL 63
#define LINE_WIDTH (LAST_COL - FIRST_COL + 1)

#define CURSOR_COL(x) (x % LINE_WIDTH + FIRST_COL)
#define CURSOR_ROW(x) (x / LINE_WIDTH + USER_FIRST_ROW)